const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('index'))
  .get('/about.ejs', (req, res) => res.render('about'))
  .get('/about1.ejs', (req, res) => res.render('about1'))
  .get('/about2.ejs', (req, res) => res.render('about2'))
  .get('/about3.ejs', (req, res) => res.render('about3'))
  .get('/about4.ejs', (req, res) => res.render('about4'))
  .get('/matching.ejs', (req, res) => res.render('matching'))
  .get('/quiz.ejs', (req, res) => res.render('quiz'))
  .get('/swot.ejs', (req, res) => res.render('swot'))
  .get('/swot1.ejs', (req, res) => res.render('swot1'))
  .get('/swot2.ejs', (req, res) => res.render('swot2'))
  .get('/swot3.ejs', (req, res) => res.render('swot3'))
  .get('/swot4.ejs', (req, res) => res.render('swot4'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
